---
language: erlang
otp_release:
- 17.4
- 18.0
- 18.2
install: true
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod 755 rebar3
script:
- bin/fetch-configlet
- bin/configlet .
- export PATH="$PATH:$PWD"
- make test
cache:
- apt
