version: 1.0.{build}
install:
- cmd: >-
    git clone -q https://github.com/rebar/rebar3.git %APPVEYOR_BUILD_FOLDER%\bin\rebar3

    cd %APPVEYOR_BUILD_FOLDER%\bin\rebar3

    .\bootstrap.bat

    cd %APPVEYOR_BUILD_FOLDER%

    curl -fsSL -o configlet.zip https://github.com/exercism/configlet/releases/download/v1.0.4/configlet-windows-32bit.zip

    7z e configlet.zip

    .\configlet.exe .
build: off
test_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    %APPVEYOR_BUILD_FOLDER%\bin\rebar3\rebar3.cmd eunit
